export interface ListElement {
  name: string
  height: number
  weight: number
  planet: string
  species: string
  gender: string
  eyes: string
  favorite: boolean
}
export const listTypes: string[] = [
  'name',
  'height',
  'weight',
  'planet',
  'species',
  'gender',
  'eyes',
  'favorite',
]

export const starWarsCharacters: ListElement[] = [
  {
    name: 'Luke Skywalker',
    height: 172,
    weight: 77,
    planet: 'Tatooine',
    species: 'Human',
    gender: 'male',
    eyes: 'blue',
    favorite: false,
  },
  {
    name: 'Darth Vader',
    height: 202,
    weight: 136,
    planet: 'Tatooine',
    species: 'Human',
    gender: 'male',
    eyes: 'yellow',
    favorite: false,
  },
  {
    name: 'Leia Organa',
    height: 150,
    weight: 49,
    planet: 'Alderaan',
    species: 'Human',
    gender: 'female',
    eyes: 'brown',
    favorite: false,
  },
  {
    name: 'Yoda',
    height: 66,
    weight: 17,
    planet: 'Unknown',
    species: "Yoda's Species",
    gender: 'male',
    eyes: 'brown',
    favorite: false,
  },
  {
    name: 'Chewbacca',
    height: 228,
    weight: 112,
    planet: 'Kashyyyk',
    species: 'Wookiee',
    gender: 'male',
    eyes: 'blue',
    favorite: false,
  },
  {
    name: 'C-3PO',
    height: 167,
    weight: 75,
    planet: 'Tatooine',
    species: 'Droid',
    gender: 'n/a',
    eyes: 'Red',
    favorite: false,
  },
  {
    name: 'Han Solo',
    height: 180,
    weight: 80,
    planet: 'Corellia',
    species: 'Human',
    gender: 'male',
    eyes: 'brown',
    favorite: false,
  },
  {
    name: 'R2-D2',
    height: 96,
    weight: 32,
    planet: 'Naboo',
    species: 'Droid',
    gender: 'n/a',
    eyes: 'Red',
    favorite: false,
  },
  {
    name: 'Lando Calrissian',
    height: 177,
    weight: 79,
    planet: 'Socorro',
    species: 'Human',
    gender: 'male',
    eyes: 'brown',
    favorite: false,
  },
  {
    name: 'Obi-Wan Kenobi',
    height: 182,
    weight: 77,
    planet: 'Stewjon',
    species: 'Human',
    gender: 'male',
    eyes: 'blue-gray',
    favorite: false,
  },
  {
    name: 'Boba Fett',
    height: 183,
    weight: 78.2,
    planet: 'Kamino',
    species: 'Human',
    gender: 'male',
    eyes: 'brown',
    favorite: false,
  },
  {
    name: 'Palpatine',
    height: 170,
    weight: 75,
    planet: 'Naboo',
    species: 'Human',
    gender: 'male',
    eyes: 'yellow',
    favorite: false,
  },
  {
    name: 'Qui-Gon Jinn',
    height: 193,
    weight: 89,
    planet: 'Cerea',
    species: 'Human',
    gender: 'male',
    eyes: 'blue',
    favorite: false,
  },
]
